### ISSUE TITLE
Outdated API data

### ISSUE THREAD

**Issue by joaobwz** [Buzzsprout/buzzsprout-api#49] opened 2024-07-09 12:27 UTC
I'm pulling the data through the API, but the data is out of date, the website shows newer numbers than in the API result (total_plays for example).

**Comment by johnloringpollard** [comment] 2024-07-10 16:45
Do you have a screenshot of what you mean by "newer numbers"?

**Comment by joaobwz** [comment] 2024-07-10 16:55
@johnloringpollard 

**total_plays** in the API response is outdated compared to the dashboard.  And weirdly, it seems that this issue doesn't occur with all podcasts.

![Screenshot 2024-07-10 135308](https://github.com/buzzsprout/buzzsprout-api/assets/119628595/e0f93fd4-2921-418b-acbe-7e33f43e2813)
![Screenshot 2024-07-10 135316](https://github.com/buzzsprout/buzzsprout-api/assets/119628595/1d6e9515-1057-4dfa-84ee-cf67d77cb652)

**Comment by tomrossi7** [comment] 2024-07-10 17:24
Was this a migrated episode with imported downloads?

**Comment by tomrossi7** [comment] 2024-07-10 19:36
I've confirmed the issue is because the episode had 20 downloads when the episode was imported. I'm looking now at having those added to the "total_plays" in the API.

**Comment by tomrossi7** [comment] 2024-07-10 20:47
A fix has been deployed that incorporates older downloads as well as imported downloads.

**Closed as completed by tomrossi7** 2024-07-10 20:47 UTC

**Comment by joaobwz** [comment] 2024-07-11 12:55
> A fix has been deployed that incorporates older downloads as well as imported downloads.

I think It's working now, thanks. I'm working in a task on this and let you know if I find any more issues.
